// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-profilerelease.fsx"
#load "../AssemblyInfo.fs"
      "../Resources.fs"
      "../OctTree.fs"
      "../FigureColor.fs"
      "../Figures.fs"
      "../FigureRendering.fs"
      "../FigureBuilding.fs"
      "../FigureHitTests.fs"
      "../FigureClipping.fs"
      "../CoreRendering.fs"
      "../CoreAlgorithms.fs"
      "../Filters.fs"
      "../CIExyYPlane.fs"
