// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "PresentationCore.dll"
#r "PresentationFramework.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Xaml.dll"
#r "UIAutomationTypes.dll"
#r "WindowsBase.dll"
#r "../packages/FSharp.Collections.ParallelSeq/lib/net40/FSharp.Collections.ParallelSeq.dll"
#r "../packages/WriteableBitmapEx/lib/net40/WriteableBitmapEx.Wpf.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.AvalonDock.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.AvalonDock.Themes.Aero.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.AvalonDock.Themes.Metro.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.AvalonDock.Themes.VS2010.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.DataGrid.dll"
#r "../packages/Extended.Wpf.Toolkit/lib/net40/Xceed.Wpf.Toolkit.dll"