// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references.fsx"
#load "../AssemblyInfo.fs"
      "../Utils.fs"
      "../FigureColor.fs"
      "../Figures.fs"
      "../FigureRendering.fs"
      "../FigureBuilding.fs"
      "../FigureHitTests.fs"
      "../FigureClipping.fs"
      "../CoreRendering.fs"
      "../CoreAlgorithms.fs"
      "../Resources.fs"
      "../UI.Utils.fs"
      "../UI.FigureInfoPicker.fs"
      "../UI.MainWindow.fs"
      "../Program.fs"
